### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by CallumWalley** [nesi/nesi-virtual-desktops#27]
Looks like websocket is being initialised twice, then failing the second time? 
Gets around the usual port checking by getting a free port, then failing.

```
WebSocket server settings:
  - Listen on localhost:56703
  - Web server. Web root: /opt/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from localhost:56703 to :66424
  - Navigate to http://localhost:56703 in web browser to connect
  - Press 'Ctrl + C' to close connection ( Note: VDT instance not persistent )
WebSocket server settings:
  - Listen on localhost:56703
  - Web server. Web root: /opt/noVNC
  - No SSL/TLS support (no cert file)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/websockify/websockify/__main__.py", line 4, in <module>
    websockify.websocketproxy.websockify_init()
  File "/opt/websockify/websockify/websocketproxy.py", line 701, in websockify_init
    server.start_server()
  File "/opt/websockify/websockify/websockifyserver.py", line 704, in start_server
    lsock = self.socket(self.listen_host, self.listen_port, False,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/websockify/websockify/websockifyserver.py", line 470, in socket
    sock.bind(addrs[0][4])
OSError: [Errno 98] Address already in use
```

**Comment by CallumWalley** [comment]
Could do with a higher level 'retry' loop.
