### ISSUE TITLE
LD_PRELOAD error

### ISSUE THREAD

**Issue by CallumWalley** [nesi/nesi-virtual-desktops#5]
Happens during first connection only.

**Comment by CallumWalley** [comment]
```
/opt/nesi/vdt/run default 14002
default 14002

Host:          mahuika02.mahuika.nesi.org.nz
Desktop:       default
Persistent:    true
Inbound Port:  14002

        n) New desktop.
        a) Adopt a SLURM session.
        q) Quit

What would you like to do?
[n/q/a]: n
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
xauth:  file /home/riom/.Xauthtority does not exist
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/opt/nesi/share/ANSYS/affxcept.so' from LD_PRELOAD cannot be preloaded: ignored.

Desktop 'TurboVNC: mahuika02.mahuika.nesi.org.nz:1801 (riom)' started on display mahuika02.mahuika.nesi.org.nz:1801

Creating default startup script /home/riom/.vnc/xstartup.turbovnc
Starting applications specified in /home/riom/.vnc/xstartup.turbovnc
Log file is /home/riom/.vnc/mahuika02.mahuika.nesi.org.nz:1801.log
Creating new session...
WebSocket server settings:
  - Listen on :14002
  - Web server. Web root: /opt/nesi/vdt/noVNC_modified
  - No SSL/TLS support (no cert file)
  - proxying from :14002 to localhost:7701
  - Now open a browser to http://localhost:14002 (assuming it was the port you forwarded.)
  - Press CTRL + C to kill.
127.0.0.1 - - [20/Jul/2020 09:09:06] code 404, message File not found
127.0.0.1 - - [20/Jul/2020 09:09:26] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [20/Jul/2020 09:09:26] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [20/Jul/2020 09:09:26] connecting to: localhost:7701
127.0.0.1 - - [20/Jul/2020 09:11:04] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [20/Jul/2020 09:11:04] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [20/Jul/2020 09:11:04] connecting to: localhost:7701
^CIn exit
Process Process-23:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Terminating child 167480
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "websockify/websockifyserver.py", line 691, in top_new_client
  File "websockify/websockifyserver.py", line 619, in do_handshake
  File "websockify/websockifyserver.py", line 99, in __init__
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "websockify/websockifyserver.py", line 315, in handle
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "websockify/websocketserver.py", line 50, in handle_one_request
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "websockify/websocketserver.py", line 60, in _websocket_do_GET
  File "websockify/websockifyserver.py", line 221, in handle_upgrade
  File "websockify/websocketserver.py", line 87, in handle_upgrade
  File "websockify/websockifyserver.py", line 259, in handle_websocket
  File "websockify/websocketproxy.py", line 134, in new_websocket_client
  File "websockify/websocketproxy.py", line 209, in do_proxy
  File "websockify/websockifyserver.py", line 678, in do_SIGINT
  File "websockify/websockifyserver.py", line 656, in terminate
Terminate
[n/q/a]: q
```

**Comment by CallumWalley** [comment]
Only seems to be in default directory. Must be fixed by something in eng start script.
